-- Storage bucket for optional member profile photos (PRD section 16, decision #8).
-- Private bucket: only the owning user can read/write their own photo via RLS;
-- admin access goes through the service-role client.
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', false)
on conflict (id) do nothing;

create policy "profile_photos_owner_read" on storage.objects for select
  using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "profile_photos_owner_write" on storage.objects for insert
  with check (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "profile_photos_owner_update" on storage.objects for update
  using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "profile_photos_owner_delete" on storage.objects for delete
  using (bucket_id = 'profile-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- Seed reference locations: world countries + full Indonesia province/city hierarchy.
-- Sources: mledoze/countries (ISO 3166-1 common names), cahyadsn/wilayah (Kemendagri codes).
-- Countries other than Indonesia are seeded at country level only; a city-level row is
-- created on demand by the application when a member outside Indonesia specifies a city
-- (see lib/db/queries/locations.ts), keeping this migration's size manageable.

insert into locations (country_code, country_name, province_code, province_name, city_code, city_name) values
('ID', 'Indonesia', null, null, null, null),
('AF', 'Afghanistan', null, null, null, null),
('AL', 'Albania', null, null, null, null),
('DZ', 'Algeria', null, null, null, null),
('AS', 'American Samoa', null, null, null, null),
('AD', 'Andorra', null, null, null, null),
('AO', 'Angola', null, null, null, null),
('AI', 'Anguilla', null, null, null, null),
('AQ', 'Antarctica', null, null, null, null),
('AG', 'Antigua and Barbuda', null, null, null, null),
('AR', 'Argentina', null, null, null, null),
('AM', 'Armenia', null, null, null, null),
('AW', 'Aruba', null, null, null, null),
('AU', 'Australia', null, null, null, null),
('AT', 'Austria', null, null, null, null),
('AZ', 'Azerbaijan', null, null, null, null),
('BS', 'Bahamas', null, null, null, null),
('BH', 'Bahrain', null, null, null, null),
('BD', 'Bangladesh', null, null, null, null),
('BB', 'Barbados', null, null, null, null),
('BY', 'Belarus', null, null, null, null),
('BE', 'Belgium', null, null, null, null),
('BZ', 'Belize', null, null, null, null),
('BJ', 'Benin', null, null, null, null),
('BM', 'Bermuda', null, null, null, null),
('BT', 'Bhutan', null, null, null, null),
('BO', 'Bolivia', null, null, null, null),
('BA', 'Bosnia and Herzegovina', null, null, null, null),
('BW', 'Botswana', null, null, null, null),
('BV', 'Bouvet Island', null, null, null, null),
('BR', 'Brazil', null, null, null, null),
('IO', 'British Indian Ocean Territory', null, null, null, null),
('VG', 'British Virgin Islands', null, null, null, null),
('BN', 'Brunei', null, null, null, null),
('BG', 'Bulgaria', null, null, null, null),
('BF', 'Burkina Faso', null, null, null, null),
('BI', 'Burundi', null, null, null, null),
('KH', 'Cambodia', null, null, null, null),
('CM', 'Cameroon', null, null, null, null),
('CA', 'Canada', null, null, null, null),
('CV', 'Cape Verde', null, null, null, null),
('BQ', 'Caribbean Netherlands', null, null, null, null),
('KY', 'Cayman Islands', null, null, null, null),
('CF', 'Central African Republic', null, null, null, null),
('TD', 'Chad', null, null, null, null),
('CL', 'Chile', null, null, null, null),
('CN', 'China', null, null, null, null),
('CX', 'Christmas Island', null, null, null, null),
('CC', 'Cocos (Keeling) Islands', null, null, null, null),
('CO', 'Colombia', null, null, null, null),
('KM', 'Comoros', null, null, null, null),
('CG', 'Congo', null, null, null, null),
('CK', 'Cook Islands', null, null, null, null),
('CR', 'Costa Rica', null, null, null, null),
('HR', 'Croatia', null, null, null, null),
('CU', 'Cuba', null, null, null, null),
('CW', 'Curaçao', null, null, null, null),
('CY', 'Cyprus', null, null, null, null),
('CZ', 'Czechia', null, null, null, null),
('CD', 'DR Congo', null, null, null, null),
('DK', 'Denmark', null, null, null, null),
('DJ', 'Djibouti', null, null, null, null),
('DM', 'Dominica', null, null, null, null),
('DO', 'Dominican Republic', null, null, null, null),
('EC', 'Ecuador', null, null, null, null),
('EG', 'Egypt', null, null, null, null),
('SV', 'El Salvador', null, null, null, null),
('GQ', 'Equatorial Guinea', null, null, null, null),
('ER', 'Eritrea', null, null, null, null),
('EE', 'Estonia', null, null, null, null),
('SZ', 'Eswatini', null, null, null, null),
('ET', 'Ethiopia', null, null, null, null),
('FK', 'Falkland Islands', null, null, null, null),
('FO', 'Faroe Islands', null, null, null, null),
('FJ', 'Fiji', null, null, null, null),
('FI', 'Finland', null, null, null, null),
('FR', 'France', null, null, null, null),
('GF', 'French Guiana', null, null, null, null),
('PF', 'French Polynesia', null, null, null, null),
('TF', 'French Southern and Antarctic Lands', null, null, null, null),
('GA', 'Gabon', null, null, null, null),
('GM', 'Gambia', null, null, null, null),
('GE', 'Georgia', null, null, null, null),
('DE', 'Germany', null, null, null, null),
('GH', 'Ghana', null, null, null, null),
('GI', 'Gibraltar', null, null, null, null),
('GR', 'Greece', null, null, null, null),
('GL', 'Greenland', null, null, null, null),
('GD', 'Grenada', null, null, null, null),
('GP', 'Guadeloupe', null, null, null, null),
('GU', 'Guam', null, null, null, null),
('GT', 'Guatemala', null, null, null, null),
('GG', 'Guernsey', null, null, null, null),
('GN', 'Guinea', null, null, null, null),
('GW', 'Guinea-Bissau', null, null, null, null),
('GY', 'Guyana', null, null, null, null),
('HT', 'Haiti', null, null, null, null),
('HM', 'Heard Island and McDonald Islands', null, null, null, null),
('HN', 'Honduras', null, null, null, null),
('HK', 'Hong Kong', null, null, null, null),
('HU', 'Hungary', null, null, null, null),
('IS', 'Iceland', null, null, null, null),
('IN', 'India', null, null, null, null),
('IR', 'Iran', null, null, null, null),
('IQ', 'Iraq', null, null, null, null),
('IE', 'Ireland', null, null, null, null),
('IM', 'Isle of Man', null, null, null, null),
('IL', 'Israel', null, null, null, null),
('IT', 'Italy', null, null, null, null),
('CI', 'Ivory Coast', null, null, null, null),
('JM', 'Jamaica', null, null, null, null),
('JP', 'Japan', null, null, null, null),
('JE', 'Jersey', null, null, null, null),
('JO', 'Jordan', null, null, null, null),
('KZ', 'Kazakhstan', null, null, null, null),
('KE', 'Kenya', null, null, null, null),
('KI', 'Kiribati', null, null, null, null),
('XK', 'Kosovo', null, null, null, null),
('KW', 'Kuwait', null, null, null, null),
('KG', 'Kyrgyzstan', null, null, null, null),
('LA', 'Laos', null, null, null, null),
('LV', 'Latvia', null, null, null, null),
('LB', 'Lebanon', null, null, null, null),
('LS', 'Lesotho', null, null, null, null),
('LR', 'Liberia', null, null, null, null),
('LY', 'Libya', null, null, null, null),
('LI', 'Liechtenstein', null, null, null, null),
('LT', 'Lithuania', null, null, null, null),
('LU', 'Luxembourg', null, null, null, null),
('MO', 'Macau', null, null, null, null),
('MG', 'Madagascar', null, null, null, null),
('MW', 'Malawi', null, null, null, null),
('MY', 'Malaysia', null, null, null, null),
('MV', 'Maldives', null, null, null, null),
('ML', 'Mali', null, null, null, null),
('MT', 'Malta', null, null, null, null),
('MH', 'Marshall Islands', null, null, null, null),
('MQ', 'Martinique', null, null, null, null),
('MR', 'Mauritania', null, null, null, null),
('MU', 'Mauritius', null, null, null, null),
('YT', 'Mayotte', null, null, null, null),
('MX', 'Mexico', null, null, null, null),
('FM', 'Micronesia', null, null, null, null),
('MD', 'Moldova', null, null, null, null),
('MC', 'Monaco', null, null, null, null),
('MN', 'Mongolia', null, null, null, null),
('ME', 'Montenegro', null, null, null, null),
('MS', 'Montserrat', null, null, null, null),
('MA', 'Morocco', null, null, null, null),
('MZ', 'Mozambique', null, null, null, null),
('MM', 'Myanmar', null, null, null, null),
('NA', 'Namibia', null, null, null, null),
('NR', 'Nauru', null, null, null, null),
('NP', 'Nepal', null, null, null, null),
('NL', 'Netherlands', null, null, null, null),
('NC', 'New Caledonia', null, null, null, null),
('NZ', 'New Zealand', null, null, null, null),
('NI', 'Nicaragua', null, null, null, null),
('NE', 'Niger', null, null, null, null),
('NG', 'Nigeria', null, null, null, null),
('NU', 'Niue', null, null, null, null),
('NF', 'Norfolk Island', null, null, null, null),
('KP', 'North Korea', null, null, null, null),
('MK', 'North Macedonia', null, null, null, null),
('MP', 'Northern Mariana Islands', null, null, null, null),
('NO', 'Norway', null, null, null, null),
('OM', 'Oman', null, null, null, null),
('PK', 'Pakistan', null, null, null, null),
('PW', 'Palau', null, null, null, null),
('PS', 'Palestine', null, null, null, null),
('PA', 'Panama', null, null, null, null),
('PG', 'Papua New Guinea', null, null, null, null),
('PY', 'Paraguay', null, null, null, null),
('PE', 'Peru', null, null, null, null),
('PH', 'Philippines', null, null, null, null),
('PN', 'Pitcairn Islands', null, null, null, null),
('PL', 'Poland', null, null, null, null),
('PT', 'Portugal', null, null, null, null),
('PR', 'Puerto Rico', null, null, null, null),
('QA', 'Qatar', null, null, null, null),
('RO', 'Romania', null, null, null, null),
('RU', 'Russia', null, null, null, null),
('RW', 'Rwanda', null, null, null, null),
('RE', 'Réunion', null, null, null, null),
('BL', 'Saint Barthélemy', null, null, null, null),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', null, null, null, null),
('KN', 'Saint Kitts and Nevis', null, null, null, null),
('LC', 'Saint Lucia', null, null, null, null),
('MF', 'Saint Martin', null, null, null, null),
('PM', 'Saint Pierre and Miquelon', null, null, null, null),
('VC', 'Saint Vincent and the Grenadines', null, null, null, null),
('WS', 'Samoa', null, null, null, null),
('SM', 'San Marino', null, null, null, null),
('SA', 'Saudi Arabia', null, null, null, null),
('SN', 'Senegal', null, null, null, null),
('RS', 'Serbia', null, null, null, null),
('SC', 'Seychelles', null, null, null, null),
('SL', 'Sierra Leone', null, null, null, null),
('SG', 'Singapore', null, null, null, null),
('SX', 'Sint Maarten', null, null, null, null),
('SK', 'Slovakia', null, null, null, null),
('SI', 'Slovenia', null, null, null, null),
('SB', 'Solomon Islands', null, null, null, null),
('SO', 'Somalia', null, null, null, null),
('ZA', 'South Africa', null, null, null, null),
('GS', 'South Georgia', null, null, null, null),
('KR', 'South Korea', null, null, null, null),
('SS', 'South Sudan', null, null, null, null),
('ES', 'Spain', null, null, null, null),
('LK', 'Sri Lanka', null, null, null, null),
('SD', 'Sudan', null, null, null, null),
('SR', 'Suriname', null, null, null, null),
('SJ', 'Svalbard and Jan Mayen', null, null, null, null),
('SE', 'Sweden', null, null, null, null),
('CH', 'Switzerland', null, null, null, null),
('SY', 'Syria', null, null, null, null),
('ST', 'São Tomé and Príncipe', null, null, null, null),
('TW', 'Taiwan', null, null, null, null),
('TJ', 'Tajikistan', null, null, null, null),
('TZ', 'Tanzania', null, null, null, null),
('TH', 'Thailand', null, null, null, null),
('TL', 'Timor-Leste', null, null, null, null),
('TG', 'Togo', null, null, null, null),
('TK', 'Tokelau', null, null, null, null),
('TO', 'Tonga', null, null, null, null),
('TT', 'Trinidad and Tobago', null, null, null, null),
('TN', 'Tunisia', null, null, null, null),
('TM', 'Turkmenistan', null, null, null, null),
('TC', 'Turks and Caicos Islands', null, null, null, null),
('TV', 'Tuvalu', null, null, null, null),
('TR', 'Türkiye', null, null, null, null),
('UG', 'Uganda', null, null, null, null),
('UA', 'Ukraine', null, null, null, null),
('AE', 'United Arab Emirates', null, null, null, null),
('GB', 'United Kingdom', null, null, null, null),
('US', 'United States', null, null, null, null),
('UM', 'United States Minor Outlying Islands', null, null, null, null),
('VI', 'United States Virgin Islands', null, null, null, null),
('UY', 'Uruguay', null, null, null, null),
('UZ', 'Uzbekistan', null, null, null, null),
('VU', 'Vanuatu', null, null, null, null),
('VA', 'Vatican City', null, null, null, null),
('VE', 'Venezuela', null, null, null, null),
('VN', 'Vietnam', null, null, null, null),
('WF', 'Wallis and Futuna', null, null, null, null),
('EH', 'Western Sahara', null, null, null, null),
('YE', 'Yemen', null, null, null, null),
('ZM', 'Zambia', null, null, null, null),
('ZW', 'Zimbabwe', null, null, null, null),
('AX', 'Åland Islands', null, null, null, null),
('ID', 'Indonesia', '11', 'Aceh', null, null),
('ID', 'Indonesia', '12', 'Sumatera Utara', null, null),
('ID', 'Indonesia', '13', 'Sumatera Barat', null, null),
('ID', 'Indonesia', '14', 'Riau', null, null),
('ID', 'Indonesia', '15', 'Jambi', null, null),
('ID', 'Indonesia', '16', 'Sumatera Selatan', null, null),
('ID', 'Indonesia', '17', 'Bengkulu', null, null),
('ID', 'Indonesia', '18', 'Lampung', null, null),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', null, null),
('ID', 'Indonesia', '21', 'Kepulauan Riau', null, null),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', null, null),
('ID', 'Indonesia', '32', 'Jawa Barat', null, null),
('ID', 'Indonesia', '33', 'Jawa Tengah', null, null),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', null, null),
('ID', 'Indonesia', '35', 'Jawa Timur', null, null),
('ID', 'Indonesia', '36', 'Banten', null, null),
('ID', 'Indonesia', '51', 'Bali', null, null),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', null, null),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', null, null),
('ID', 'Indonesia', '61', 'Kalimantan Barat', null, null),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', null, null),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', null, null),
('ID', 'Indonesia', '64', 'Kalimantan Timur', null, null),
('ID', 'Indonesia', '65', 'Kalimantan Utara', null, null),
('ID', 'Indonesia', '71', 'Sulawesi Utara', null, null),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', null, null),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', null, null),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', null, null),
('ID', 'Indonesia', '75', 'Gorontalo', null, null),
('ID', 'Indonesia', '76', 'Sulawesi Barat', null, null),
('ID', 'Indonesia', '81', 'Maluku', null, null),
('ID', 'Indonesia', '82', 'Maluku Utara', null, null),
('ID', 'Indonesia', '91', 'Papua', null, null),
('ID', 'Indonesia', '92', 'Papua Barat', null, null),
('ID', 'Indonesia', '93', 'Papua Selatan', null, null),
('ID', 'Indonesia', '94', 'Papua Tengah', null, null),
('ID', 'Indonesia', '95', 'Papua Pegunungan', null, null),
('ID', 'Indonesia', '96', 'Papua Barat Daya', null, null),
('ID', 'Indonesia', '11', 'Aceh', '11.01', 'Kabupaten Aceh Selatan'),
('ID', 'Indonesia', '11', 'Aceh', '11.02', 'Kabupaten Aceh Tenggara'),
('ID', 'Indonesia', '11', 'Aceh', '11.03', 'Kabupaten Aceh Timur'),
('ID', 'Indonesia', '11', 'Aceh', '11.04', 'Kabupaten Aceh Tengah'),
('ID', 'Indonesia', '11', 'Aceh', '11.05', 'Kabupaten Aceh Barat'),
('ID', 'Indonesia', '11', 'Aceh', '11.06', 'Kabupaten Aceh Besar'),
('ID', 'Indonesia', '11', 'Aceh', '11.07', 'Kabupaten Pidie'),
('ID', 'Indonesia', '11', 'Aceh', '11.08', 'Kabupaten Aceh Utara'),
('ID', 'Indonesia', '11', 'Aceh', '11.09', 'Kabupaten Simeulue'),
('ID', 'Indonesia', '11', 'Aceh', '11.10', 'Kabupaten Aceh Singkil'),
('ID', 'Indonesia', '11', 'Aceh', '11.11', 'Kabupaten Bireuen'),
('ID', 'Indonesia', '11', 'Aceh', '11.12', 'Kabupaten Aceh Barat Daya'),
('ID', 'Indonesia', '11', 'Aceh', '11.13', 'Kabupaten Gayo Lues'),
('ID', 'Indonesia', '11', 'Aceh', '11.14', 'Kabupaten Aceh Jaya'),
('ID', 'Indonesia', '11', 'Aceh', '11.15', 'Kabupaten Nagan Raya'),
('ID', 'Indonesia', '11', 'Aceh', '11.16', 'Kabupaten Aceh Tamiang'),
('ID', 'Indonesia', '11', 'Aceh', '11.17', 'Kabupaten Bener Meriah'),
('ID', 'Indonesia', '11', 'Aceh', '11.18', 'Kabupaten Pidie Jaya'),
('ID', 'Indonesia', '11', 'Aceh', '11.71', 'Kota Banda Aceh'),
('ID', 'Indonesia', '11', 'Aceh', '11.72', 'Kota Sabang'),
('ID', 'Indonesia', '11', 'Aceh', '11.73', 'Kota Lhokseumawe'),
('ID', 'Indonesia', '11', 'Aceh', '11.74', 'Kota Langsa'),
('ID', 'Indonesia', '11', 'Aceh', '11.75', 'Kota Subulussalam'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.01', 'Kabupaten Tapanuli Tengah'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.02', 'Kabupaten Tapanuli Utara'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.03', 'Kabupaten Tapanuli Selatan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.04', 'Kabupaten Nias'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.05', 'Kabupaten Langkat'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.06', 'Kabupaten Karo'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.07', 'Kabupaten Deli Serdang'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.08', 'Kabupaten Simalungun'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.09', 'Kabupaten Asahan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.10', 'Kabupaten Labuhanbatu'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.11', 'Kabupaten Dairi'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.12', 'Kabupaten Toba'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.13', 'Kabupaten Mandailing Natal'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.14', 'Kabupaten Nias Selatan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.15', 'Kabupaten Pakpak Bharat'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.16', 'Kabupaten Humbang Hasundutan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.17', 'Kabupaten Samosir'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.18', 'Kabupaten Serdang Bedagai'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.19', 'Kabupaten Batu Bara'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.20', 'Kabupaten Padang Lawas Utara'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.21', 'Kabupaten Padang Lawas'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.22', 'Kabupaten Labuhanbatu Selatan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.23', 'Kabupaten Labuhanbatu Utara'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.24', 'Kabupaten Nias Utara'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.25', 'Kabupaten Nias Barat'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.71', 'Kota Medan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.72', 'Kota Pematangsiantar'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.73', 'Kota Sibolga'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.74', 'Kota Tanjungbalai'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.75', 'Kota Binjai'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.76', 'Kota Tebing Tinggi'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.77', 'Kota Padangsidimpuan'),
('ID', 'Indonesia', '12', 'Sumatera Utara', '12.78', 'Kota Gunungsitoli'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.01', 'Kabupaten Pesisir Selatan'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.02', 'Kabupaten Solok'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.03', 'Kabupaten Sijunjung'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.04', 'Kabupaten Tanah Datar'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.05', 'Kabupaten Padang Pariaman'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.06', 'Kabupaten Agam'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.07', 'Kabupaten Lima Puluh Kota'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.08', 'Kabupaten Pasaman'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.09', 'Kabupaten Kepulauan Mentawai'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.10', 'Kabupaten Dharmasraya'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.11', 'Kabupaten Solok Selatan'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.12', 'Kabupaten Pasaman Barat'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.71', 'Kota Padang'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.72', 'Kota Solok'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.73', 'Kota Sawahlunto'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.74', 'Kota Padang Panjang'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.75', 'Kota Bukittinggi'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.76', 'Kota Payakumbuh'),
('ID', 'Indonesia', '13', 'Sumatera Barat', '13.77', 'Kota Pariaman'),
('ID', 'Indonesia', '14', 'Riau', '14.01', 'Kabupaten Kampar'),
('ID', 'Indonesia', '14', 'Riau', '14.02', 'Kabupaten Indragiri Hulu'),
('ID', 'Indonesia', '14', 'Riau', '14.03', 'Kabupaten Bengkalis'),
('ID', 'Indonesia', '14', 'Riau', '14.04', 'Kabupaten Indragiri Hilir'),
('ID', 'Indonesia', '14', 'Riau', '14.05', 'Kabupaten Pelalawan'),
('ID', 'Indonesia', '14', 'Riau', '14.06', 'Kabupaten Rokan Hulu'),
('ID', 'Indonesia', '14', 'Riau', '14.07', 'Kabupaten Rokan Hilir'),
('ID', 'Indonesia', '14', 'Riau', '14.08', 'Kabupaten Siak'),
('ID', 'Indonesia', '14', 'Riau', '14.09', 'Kabupaten Kuantan Singingi'),
('ID', 'Indonesia', '14', 'Riau', '14.10', 'Kabupaten Kepulauan Meranti'),
('ID', 'Indonesia', '14', 'Riau', '14.71', 'Kota Pekanbaru'),
('ID', 'Indonesia', '14', 'Riau', '14.72', 'Kota Dumai'),
('ID', 'Indonesia', '15', 'Jambi', '15.01', 'Kabupaten Kerinci'),
('ID', 'Indonesia', '15', 'Jambi', '15.02', 'Kabupaten Merangin'),
('ID', 'Indonesia', '15', 'Jambi', '15.03', 'Kabupaten Sarolangun'),
('ID', 'Indonesia', '15', 'Jambi', '15.04', 'Kabupaten Batanghari'),
('ID', 'Indonesia', '15', 'Jambi', '15.05', 'Kabupaten Muaro Jambi'),
('ID', 'Indonesia', '15', 'Jambi', '15.06', 'Kabupaten Tanjung Jabung Barat'),
('ID', 'Indonesia', '15', 'Jambi', '15.07', 'Kabupaten Tanjung Jabung Timur'),
('ID', 'Indonesia', '15', 'Jambi', '15.08', 'Kabupaten Bungo'),
('ID', 'Indonesia', '15', 'Jambi', '15.09', 'Kabupaten Tebo'),
('ID', 'Indonesia', '15', 'Jambi', '15.71', 'Kota Jambi'),
('ID', 'Indonesia', '15', 'Jambi', '15.72', 'Kota Sungai Penuh'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.01', 'Kabupaten Ogan Komering Ulu'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.02', 'Kabupaten Ogan Komering Ilir'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.03', 'Kabupaten Muara Enim'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.04', 'Kabupaten Lahat'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.05', 'Kabupaten Musi Rawas'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.06', 'Kabupaten Musi Banyuasin'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.07', 'Kabupaten Banyuasin'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.08', 'Kabupaten Ogan Komering Ulu Timur'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.09', 'Kabupaten Ogan Komering Ulu Selatan'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.10', 'Kabupaten Ogan Ilir'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.11', 'Kabupaten Empat Lawang'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.12', 'Kabupaten Penukal Abab Lematang Ilir'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.13', 'Kabupaten Musi Rawas Utara'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.71', 'Kota Palembang'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.72', 'Kota Pagar Alam'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.73', 'Kota Lubuk Linggau'),
('ID', 'Indonesia', '16', 'Sumatera Selatan', '16.74', 'Kota Prabumulih'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.01', 'Kabupaten Bengkulu Selatan'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.02', 'Kabupaten Rejang Lebong'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.03', 'Kabupaten Bengkulu Utara'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.04', 'Kabupaten Kaur'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.05', 'Kabupaten Seluma'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.06', 'Kabupaten Mukomuko'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.07', 'Kabupaten Lebong'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.08', 'Kabupaten Kepahiang'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.09', 'Kabupaten Bengkulu Tengah'),
('ID', 'Indonesia', '17', 'Bengkulu', '17.71', 'Kota Bengkulu'),
('ID', 'Indonesia', '18', 'Lampung', '18.01', 'Kabupaten Lampung Selatan'),
('ID', 'Indonesia', '18', 'Lampung', '18.02', 'Kabupaten Lampung Tengah'),
('ID', 'Indonesia', '18', 'Lampung', '18.03', 'Kabupaten Lampung Utara'),
('ID', 'Indonesia', '18', 'Lampung', '18.04', 'Kabupaten Lampung Barat'),
('ID', 'Indonesia', '18', 'Lampung', '18.05', 'Kabupaten Tulang Bawang'),
('ID', 'Indonesia', '18', 'Lampung', '18.06', 'Kabupaten Tanggamus'),
('ID', 'Indonesia', '18', 'Lampung', '18.07', 'Kabupaten Lampung Timur'),
('ID', 'Indonesia', '18', 'Lampung', '18.08', 'Kabupaten Way Kanan'),
('ID', 'Indonesia', '18', 'Lampung', '18.09', 'Kabupaten Pesawaran'),
('ID', 'Indonesia', '18', 'Lampung', '18.10', 'Kabupaten Pringsewu'),
('ID', 'Indonesia', '18', 'Lampung', '18.11', 'Kabupaten Mesuji'),
('ID', 'Indonesia', '18', 'Lampung', '18.12', 'Kabupaten Tulang Bawang Barat'),
('ID', 'Indonesia', '18', 'Lampung', '18.13', 'Kabupaten Pesisir Barat'),
('ID', 'Indonesia', '18', 'Lampung', '18.71', 'Kota Bandar Lampung'),
('ID', 'Indonesia', '18', 'Lampung', '18.72', 'Kota Metro'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.01', 'Kabupaten Bangka'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.02', 'Kabupaten Belitung'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.03', 'Kabupaten Bangka Selatan'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.04', 'Kabupaten Bangka Tengah'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.05', 'Kabupaten Bangka Barat'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.06', 'Kabupaten Belitung Timur'),
('ID', 'Indonesia', '19', 'Kepulauan Bangka Belitung', '19.71', 'Kota Pangkal Pinang'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.01', 'Kabupaten Bintan'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.02', 'Kabupaten Karimun'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.03', 'Kabupaten Natuna'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.04', 'Kabupaten Lingga'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.05', 'Kabupaten Kepulauan Anambas'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.71', 'Kota Batam'),
('ID', 'Indonesia', '21', 'Kepulauan Riau', '21.72', 'Kota Tanjung Pinang'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.01', 'Kabupaten Administrasi Kepulauan Seribu'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.71', 'Kota Administrasi Jakarta Pusat'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.72', 'Kota Administrasi Jakarta Utara'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.73', 'Kota Administrasi Jakarta Barat'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.74', 'Kota Administrasi Jakarta Selatan'),
('ID', 'Indonesia', '31', 'Daerah Khusus Ibukota Jakarta', '31.75', 'Kota Administrasi Jakarta Timur'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.01', 'Kabupaten Bogor'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.02', 'Kabupaten Sukabumi'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.03', 'Kabupaten Cianjur'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.04', 'Kabupaten Bandung'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.05', 'Kabupaten Garut'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.06', 'Kabupaten Tasikmalaya'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.07', 'Kabupaten Ciamis'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.08', 'Kabupaten Kuningan'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.09', 'Kabupaten Cirebon'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.10', 'Kabupaten Majalengka'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.11', 'Kabupaten Sumedang'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.12', 'Kabupaten Indramayu'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.13', 'Kabupaten Subang'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.14', 'Kabupaten Purwakarta'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.15', 'Kabupaten Karawang'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.16', 'Kabupaten Bekasi'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.17', 'Kabupaten Bandung Barat'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.18', 'Kabupaten Pangandaran'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.71', 'Kota Bogor'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.72', 'Kota Sukabumi'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.73', 'Kota Bandung'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.74', 'Kota Cirebon'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.75', 'Kota Bekasi'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.76', 'Kota Depok'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.77', 'Kota Cimahi'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.78', 'Kota Tasikmalaya'),
('ID', 'Indonesia', '32', 'Jawa Barat', '32.79', 'Kota Banjar'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.01', 'Kabupaten Cilacap'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.02', 'Kabupaten Banyumas'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.03', 'Kabupaten Purbalingga'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.04', 'Kabupaten Banjarnegara'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.05', 'Kabupaten Kebumen'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.06', 'Kabupaten Purworejo'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.07', 'Kabupaten Wonosobo'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.08', 'Kabupaten Magelang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.09', 'Kabupaten Boyolali'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.10', 'Kabupaten Klaten'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.11', 'Kabupaten Sukoharjo'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.12', 'Kabupaten Wonogiri'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.13', 'Kabupaten Karanganyar'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.14', 'Kabupaten Sragen'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.15', 'Kabupaten Grobogan'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.16', 'Kabupaten Blora'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.17', 'Kabupaten Rembang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.18', 'Kabupaten Pati'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.19', 'Kabupaten Kudus'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.20', 'Kabupaten Jepara'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.21', 'Kabupaten Demak'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.22', 'Kabupaten Semarang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.23', 'Kabupaten Temanggung'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.24', 'Kabupaten Kendal'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.25', 'Kabupaten Batang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.26', 'Kabupaten Pekalongan'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.27', 'Kabupaten Pemalang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.28', 'Kabupaten Tegal'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.29', 'Kabupaten Brebes'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.71', 'Kota Magelang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.72', 'Kota Surakarta'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.73', 'Kota Salatiga'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.74', 'Kota Semarang'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.75', 'Kota Pekalongan'),
('ID', 'Indonesia', '33', 'Jawa Tengah', '33.76', 'Kota Tegal'),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', '34.01', 'Kabupaten Kulon Progo'),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', '34.02', 'Kabupaten Bantul'),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', '34.03', 'Kabupaten Gunungkidul'),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', '34.04', 'Kabupaten Sleman'),
('ID', 'Indonesia', '34', 'Daerah Istimewa Yogyakarta', '34.71', 'Kota Yogyakarta'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.01', 'Kabupaten Pacitan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.02', 'Kabupaten Ponorogo'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.03', 'Kabupaten Trenggalek'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.04', 'Kabupaten Tulungagung'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.05', 'Kabupaten Blitar'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.06', 'Kabupaten Kediri'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.07', 'Kabupaten Malang'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.08', 'Kabupaten Lumajang'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.09', 'Kabupaten Jember'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.10', 'Kabupaten Banyuwangi'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.11', 'Kabupaten Bondowoso'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.12', 'Kabupaten Situbondo'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.13', 'Kabupaten Probolinggo'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.14', 'Kabupaten Pasuruan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.15', 'Kabupaten Sidoarjo'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.16', 'Kabupaten Mojokerto'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.17', 'Kabupaten Jombang'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.18', 'Kabupaten Nganjuk'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.19', 'Kabupaten Madiun'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.20', 'Kabupaten Magetan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.21', 'Kabupaten Ngawi'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.22', 'Kabupaten Bojonegoro'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.23', 'Kabupaten Tuban'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.24', 'Kabupaten Lamongan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.25', 'Kabupaten Gresik'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.26', 'Kabupaten Bangkalan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.27', 'Kabupaten Sampang'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.28', 'Kabupaten Pamekasan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.29', 'Kabupaten Sumenep'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.71', 'Kota Kediri'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.72', 'Kota Blitar'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.73', 'Kota Malang'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.74', 'Kota Probolinggo'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.75', 'Kota Pasuruan'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.76', 'Kota Mojokerto'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.77', 'Kota Madiun'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.78', 'Kota Surabaya'),
('ID', 'Indonesia', '35', 'Jawa Timur', '35.79', 'Kota Batu'),
('ID', 'Indonesia', '36', 'Banten', '36.01', 'Kabupaten Pandeglang'),
('ID', 'Indonesia', '36', 'Banten', '36.02', 'Kabupaten Lebak'),
('ID', 'Indonesia', '36', 'Banten', '36.03', 'Kabupaten Tangerang'),
('ID', 'Indonesia', '36', 'Banten', '36.04', 'Kabupaten Serang'),
('ID', 'Indonesia', '36', 'Banten', '36.71', 'Kota Tangerang'),
('ID', 'Indonesia', '36', 'Banten', '36.72', 'Kota Cilegon'),
('ID', 'Indonesia', '36', 'Banten', '36.73', 'Kota Serang'),
('ID', 'Indonesia', '36', 'Banten', '36.74', 'Kota Tangerang Selatan'),
('ID', 'Indonesia', '51', 'Bali', '51.01', 'Kabupaten Jembrana'),
('ID', 'Indonesia', '51', 'Bali', '51.02', 'Kabupaten Tabanan'),
('ID', 'Indonesia', '51', 'Bali', '51.03', 'Kabupaten Badung'),
('ID', 'Indonesia', '51', 'Bali', '51.04', 'Kabupaten Gianyar'),
('ID', 'Indonesia', '51', 'Bali', '51.05', 'Kabupaten Klungkung'),
('ID', 'Indonesia', '51', 'Bali', '51.06', 'Kabupaten Bangli'),
('ID', 'Indonesia', '51', 'Bali', '51.07', 'Kabupaten Karangasem'),
('ID', 'Indonesia', '51', 'Bali', '51.08', 'Kabupaten Buleleng'),
('ID', 'Indonesia', '51', 'Bali', '51.71', 'Kota Denpasar'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.01', 'Kabupaten Lombok Barat'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.02', 'Kabupaten Lombok Tengah'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.03', 'Kabupaten Lombok Timur'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.04', 'Kabupaten Sumbawa'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.05', 'Kabupaten Dompu'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.06', 'Kabupaten Bima'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.07', 'Kabupaten Sumbawa Barat'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.08', 'Kabupaten Lombok Utara'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.71', 'Kota Mataram'),
('ID', 'Indonesia', '52', 'Nusa Tenggara Barat', '52.72', 'Kota Bima'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.01', 'Kabupaten Kupang'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.02', 'Kabupaten Timor Tengah Selatan'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.03', 'Kabupaten Timor Tengah Utara'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.04', 'Kabupaten Belu'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.05', 'Kabupaten Alor'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.06', 'Kabupaten Flores Timur'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.07', 'Kabupaten Sikka'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.08', 'Kabupaten Ende'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.09', 'Kabupaten Ngada'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.10', 'Kabupaten Manggarai'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.11', 'Kabupaten Sumba Timur'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.12', 'Kabupaten Sumba Barat'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.13', 'Kabupaten Lembata'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.14', 'Kabupaten Rote Ndao'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.15', 'Kabupaten Manggarai Barat'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.16', 'Kabupaten Nagekeo'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.17', 'Kabupaten Sumba Tengah'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.18', 'Kabupaten Sumba Barat Daya'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.19', 'Kabupaten Manggarai Timur'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.20', 'Kabupaten Sabu Raijua'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.21', 'Kabupaten Malaka'),
('ID', 'Indonesia', '53', 'Nusa Tenggara Timur', '53.71', 'Kota Kupang'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.01', 'Kabupaten Sambas'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.02', 'Kabupaten Mempawah'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.03', 'Kabupaten Sanggau'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.04', 'Kabupaten Ketapang'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.05', 'Kabupaten Sintang'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.06', 'Kabupaten Kapuas Hulu'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.07', 'Kabupaten Bengkayang'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.08', 'Kabupaten Landak'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.09', 'Kabupaten Sekadau'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.10', 'Kabupaten Melawi'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.11', 'Kabupaten Kayong Utara'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.12', 'Kabupaten Kubu Raya'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.71', 'Kota Pontianak'),
('ID', 'Indonesia', '61', 'Kalimantan Barat', '61.72', 'Kota Singkawang'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.01', 'Kabupaten Kotawaringin Barat'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.02', 'Kabupaten Kotawaringin Timur'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.03', 'Kabupaten Kapuas'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.04', 'Kabupaten Barito Selatan'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.05', 'Kabupaten Barito Utara'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.06', 'Kabupaten Katingan'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.07', 'Kabupaten Seruyan'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.08', 'Kabupaten Sukamara'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.09', 'Kabupaten Lamandau'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.10', 'Kabupaten Gunung Mas'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.11', 'Kabupaten Pulang Pisau'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.12', 'Kabupaten Murung Raya'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.13', 'Kabupaten Barito Timur'),
('ID', 'Indonesia', '62', 'Kalimantan Tengah', '62.71', 'Kota Palangkaraya'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.01', 'Kabupaten Tanah Laut'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.02', 'Kabupaten Kotabaru'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.03', 'Kabupaten Banjar'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.04', 'Kabupaten Barito Kuala'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.05', 'Kabupaten Tapin'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.06', 'Kabupaten Hulu Sungai Selatan'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.07', 'Kabupaten Hulu Sungai Tengah'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.08', 'Kabupaten Hulu Sungai Utara'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.09', 'Kabupaten Tabalong'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.10', 'Kabupaten Tanah Bumbu'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.11', 'Kabupaten Balangan'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.71', 'Kota Banjarmasin'),
('ID', 'Indonesia', '63', 'Kalimantan Selatan', '63.72', 'Kota Banjarbaru'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.01', 'Kabupaten Paser'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.02', 'Kabupaten Kutai Kartanegara'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.03', 'Kabupaten Berau'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.07', 'Kabupaten Kutai Barat'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.08', 'Kabupaten Kutai Timur'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.09', 'Kabupaten Penajam Paser Utara'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.11', 'Kabupaten Mahakam Ulu'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.71', 'Kota Balikpapan'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.72', 'Kota Samarinda'),
('ID', 'Indonesia', '64', 'Kalimantan Timur', '64.74', 'Kota Bontang'),
('ID', 'Indonesia', '65', 'Kalimantan Utara', '65.01', 'Kabupaten Bulungan'),
('ID', 'Indonesia', '65', 'Kalimantan Utara', '65.02', 'Kabupaten Malinau'),
('ID', 'Indonesia', '65', 'Kalimantan Utara', '65.03', 'Kabupaten Nunukan'),
('ID', 'Indonesia', '65', 'Kalimantan Utara', '65.04', 'Kabupaten Tana Tidung'),
('ID', 'Indonesia', '65', 'Kalimantan Utara', '65.71', 'Kota Tarakan'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.01', 'Kabupaten Bolaang Mongondow'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.02', 'Kabupaten Minahasa'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.03', 'Kabupaten Kepulauan Sangihe'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.04', 'Kabupaten Kepulauan Talaud'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.05', 'Kabupaten Minahasa Selatan'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.06', 'Kabupaten Minahasa Utara'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.07', 'Kabupaten Minahasa Tenggara'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.08', 'Kabupaten Bolaang Mongondow Utara'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.09', 'Kabupaten Kep. Siau Tagulandang Biaro'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.10', 'Kabupaten Bolaang Mongondow Timur'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.11', 'Kabupaten Bolaang Mongondow Selatan'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.71', 'Kota Manado'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.72', 'Kota Bitung'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.73', 'Kota Tomohon'),
('ID', 'Indonesia', '71', 'Sulawesi Utara', '71.74', 'Kota Kotamobagu'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.01', 'Kabupaten Banggai'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.02', 'Kabupaten Poso'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.03', 'Kabupaten Donggala'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.04', 'Kabupaten Toli-Toli'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.05', 'Kabupaten Buol'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.06', 'Kabupaten Morowali'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.07', 'Kabupaten Banggai Kepulauan'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.08', 'Kabupaten Parigi Moutong'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.09', 'Kabupaten Tojo Una Una'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.10', 'Kabupaten Sigi'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.11', 'Kabupaten Banggai Laut'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.12', 'Kabupaten Morowali Utara'),
('ID', 'Indonesia', '72', 'Sulawesi Tengah', '72.71', 'Kota Palu'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.01', 'Kabupaten Kepulauan Selayar'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.02', 'Kabupaten Bulukumba'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.03', 'Kabupaten Bantaeng'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.04', 'Kabupaten Jeneponto'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.05', 'Kabupaten Takalar'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.06', 'Kabupaten Gowa'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.07', 'Kabupaten Sinjai'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.08', 'Kabupaten Bone'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.09', 'Kabupaten Maros'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.10', 'Kabupaten Pangkajene dan Kepulauan'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.11', 'Kabupaten Barru'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.12', 'Kabupaten Soppeng'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.13', 'Kabupaten Wajo'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.14', 'Kabupaten Sidenreng Rappang'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.15', 'Kabupaten Pinrang'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.16', 'Kabupaten Enrekang'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.17', 'Kabupaten Luwu'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.18', 'Kabupaten Tana Toraja'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.22', 'Kabupaten Luwu Utara'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.24', 'Kabupaten Luwu Timur'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.26', 'Kabupaten Toraja Utara'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.71', 'Kota Makassar'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.72', 'Kota Parepare'),
('ID', 'Indonesia', '73', 'Sulawesi Selatan', '73.73', 'Kota Palopo'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.01', 'Kabupaten Kolaka'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.02', 'Kabupaten Konawe'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.03', 'Kabupaten Muna'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.04', 'Kabupaten Buton'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.05', 'Kabupaten Konawe Selatan'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.06', 'Kabupaten Bombana'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.07', 'Kabupaten Wakatobi'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.08', 'Kabupaten Kolaka Utara'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.09', 'Kabupaten Konawe Utara'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.10', 'Kabupaten Buton Utara'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.11', 'Kabupaten Kolaka Timur'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.12', 'Kabupaten Konawe Kepulauan'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.13', 'Kabupaten Muna Barat'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.14', 'Kabupaten Buton Tengah'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.15', 'Kabupaten Buton Selatan'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.71', 'Kota Kendari'),
('ID', 'Indonesia', '74', 'Sulawesi Tenggara', '74.72', 'Kota Bau Bau'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.01', 'Kabupaten Gorontalo'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.02', 'Kabupaten Boalemo'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.03', 'Kabupaten Bone Bolango'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.04', 'Kabupaten Pohuwato'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.05', 'Kabupaten Gorontalo Utara'),
('ID', 'Indonesia', '75', 'Gorontalo', '75.71', 'Kota Gorontalo'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.01', 'Kabupaten Pasangkayu'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.02', 'Kabupaten Mamuju'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.03', 'Kabupaten Mamasa'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.04', 'Kabupaten Polewali Mandar'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.05', 'Kabupaten Majene'),
('ID', 'Indonesia', '76', 'Sulawesi Barat', '76.06', 'Kabupaten Mamuju Tengah'),
('ID', 'Indonesia', '81', 'Maluku', '81.01', 'Kabupaten Maluku Tengah'),
('ID', 'Indonesia', '81', 'Maluku', '81.02', 'Kabupaten Maluku Tenggara'),
('ID', 'Indonesia', '81', 'Maluku', '81.03', 'Kabupaten Kepulauan Tanimbar'),
('ID', 'Indonesia', '81', 'Maluku', '81.04', 'Kabupaten Buru'),
('ID', 'Indonesia', '81', 'Maluku', '81.05', 'Kabupaten Seram Bagian Timur'),
('ID', 'Indonesia', '81', 'Maluku', '81.06', 'Kabupaten Seram Bagian Barat'),
('ID', 'Indonesia', '81', 'Maluku', '81.07', 'Kabupaten Kepulauan Aru'),
('ID', 'Indonesia', '81', 'Maluku', '81.08', 'Kabupaten Maluku Barat Daya'),
('ID', 'Indonesia', '81', 'Maluku', '81.09', 'Kabupaten Buru Selatan'),
('ID', 'Indonesia', '81', 'Maluku', '81.71', 'Kota Ambon'),
('ID', 'Indonesia', '81', 'Maluku', '81.72', 'Kota Tual'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.01', 'Kabupaten Halmahera Barat'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.02', 'Kabupaten Halmahera Tengah'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.03', 'Kabupaten Halmahera Utara'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.04', 'Kabupaten Halmahera Selatan'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.05', 'Kabupaten Kepulauan Sula'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.06', 'Kabupaten Halmahera Timur'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.07', 'Kabupaten Pulau Morotai'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.08', 'Kabupaten Pulau Taliabu'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.71', 'Kota Ternate'),
('ID', 'Indonesia', '82', 'Maluku Utara', '82.72', 'Kota Tidore Kepulauan'),
('ID', 'Indonesia', '91', 'Papua', '91.03', 'Kabupaten Jayapura'),
('ID', 'Indonesia', '91', 'Papua', '91.05', 'Kabupaten Kepulauan Yapen'),
('ID', 'Indonesia', '91', 'Papua', '91.06', 'Kabupaten Biak Numfor'),
('ID', 'Indonesia', '91', 'Papua', '91.10', 'Kabupaten Sarmi'),
('ID', 'Indonesia', '91', 'Papua', '91.11', 'Kabupaten Keerom'),
('ID', 'Indonesia', '91', 'Papua', '91.15', 'Kabupaten Waropen'),
('ID', 'Indonesia', '91', 'Papua', '91.19', 'Kabupaten Supiori'),
('ID', 'Indonesia', '91', 'Papua', '91.20', 'Kabupaten Mamberamo Raya'),
('ID', 'Indonesia', '91', 'Papua', '91.71', 'Kota Jayapura'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.02', 'Kabupaten Manokwari'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.03', 'Kabupaten Fak Fak'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.06', 'Kabupaten Teluk Bintuni'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.07', 'Kabupaten Teluk Wondama'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.08', 'Kabupaten Kaimana'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.11', 'Kabupaten Manokwari Selatan'),
('ID', 'Indonesia', '92', 'Papua Barat', '92.12', 'Kabupaten Pegunungan Arfak'),
('ID', 'Indonesia', '93', 'Papua Selatan', '93.01', 'Kabupaten Merauke'),
('ID', 'Indonesia', '93', 'Papua Selatan', '93.02', 'Kabupaten Boven Digoel'),
('ID', 'Indonesia', '93', 'Papua Selatan', '93.03', 'Kabupaten Mappi'),
('ID', 'Indonesia', '93', 'Papua Selatan', '93.04', 'Kabupaten Asmat'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.01', 'Kabupaten Nabire'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.02', 'Kabupaten Puncak Jaya'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.03', 'Kabupaten Paniai'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.04', 'Kabupaten Mimika'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.05', 'Kabupaten Puncak'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.06', 'Kabupaten Dogiyai'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.07', 'Kabupaten Intan Jaya'),
('ID', 'Indonesia', '94', 'Papua Tengah', '94.08', 'Kabupaten Deiyai'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.01', 'Kabupaten Jayawijaya'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.02', 'Kabupaten Pegunungan Bintang'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.03', 'Kabupaten Yahukimo'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.04', 'Kabupaten Tolikara'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.05', 'Kabupaten Mamberamo Tengah'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.06', 'Kabupaten Yalimo'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.07', 'Kabupaten Lanny Jaya'),
('ID', 'Indonesia', '95', 'Papua Pegunungan', '95.08', 'Kabupaten Nduga'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.01', 'Kabupaten Sorong'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.02', 'Kabupaten Sorong Selatan'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.03', 'Kabupaten Raja Ampat'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.04', 'Kabupaten Tambrauw'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.05', 'Kabupaten Maybrat'),
('ID', 'Indonesia', '96', 'Papua Barat Daya', '96.71', 'Kota Sorong');
